# Presetup for WindowsFeature
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  tasks:
  - debug: msg="User is {{ user }}"
  - name: Install PIP and Related
    shell: yum install -y gcc libffi-devel python-devel krb5-devel krb5-libs krb5-workstation
  - name: Add yumutils
    shell: yum install -y yum-utils
  - name: Enable Extras
    shell: yum-config-manager --enable rhel-7-server-extras-rpms
  - name: Enable EPEL
    shell: yum install -y  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm || true
    ignore_errors: yes
  - name: Install PIP and Related
    shell: yum install -y python-pip
  - name: disable epel
    shell: yum-config-manager --disable epel
  - name: Install pywinrm
    shell: pip install "pywinrm" --upgrade 
  - name: Install pywinrm keberos
    shell: pip install pywinrm[kerberos] --upgrade
# Make sure basic components needed for Windows are Auto Installed and Updates Done
- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
     ipv6cmd: !unsafe New-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\' -Name  'DisabledComponents' -Value '0xffffffff' -PropertyType 'DWord'
  tasks:
  - name: Check Comm
    win_ping:
  - name: Disable Extra IP Stack
    win_shell: "{{ipv6cmd}}"
    ignore_errors: yes
  - name: Rename Computer
    win_shell: Rename-Computer -NewName "{{inventory_hostname}}" -Force
    ignore_errors: yes
  - name: Restart Windows Nodes (For rename)
    win_reboot:
        reboot_timeout: 3600
  - name: Install HyperV
    win_shell: Install-WindowsFeature -Name Hyper-V, RSAT-Hyper-V-Tools
    ignore_errors: yes
  - name: Install the Nuget provider
    win_shell: Find-PackageProvider -Name "Nuget" | Install-PackageProvider -Verbose -Force
  - name: Install Package Manager Provider
    win_shell: Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
  - name: Install Docker Provider
    win_shell: Install-Package -Name docker -ProviderName DockerMsftProvider -Confirm
  - name: Install Docker
    win_shell: Install-Package Docker -ProviderName DockerMsftProvider -Force
  - name: Windows Update
    win_shell: Install-Package PSWindowsUpdate -Force
  - name: Do updates
    win_shell: Get-WUInstall -AcceptAll
  - name: Restart Windows Nodes
    win_reboot:
        reboot_timeout: 3600
  - name: Sleep a while to make sure we are done with restart from update
    pause:
       minutes: 1
- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  vars_files:
   - /etc/ansible/parameters.vars
  tasks:
  - name: Remove Old Bin if it exists
    win_file:
       path: c:\bin
       state: absent
  - name: Create Bin Directory
    win_file:
       path: c:\bin
       state: directory
  - name: Set Bin Path
    win_shell: setx ChocolateyBinRoot "C:\bin" -m
  - name: Set Path
    win_shell: setx PATH "C:\ProgramData\chocolatey\bin;$env:path;c:\bin;c:\k\hybrid\3.9\bin" -m
  - name: Cleanup old K Directory
    win_file:
       path: c:\k
       state: absent
  - name: Create K Directory
    win_file:
       path: c:\k
       state: directory
  - name: Install Package Manager
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
  - name: Install 7zip
    win_shell: choco install 7zip.portable -y
  - name: Install Vim
    win_shell: choco install vim -y
    retries: 3
    delay: 5
  - name: Install git
    win_shell: choco install git -y
    retries: 3
    delay: 5
  - name: Install wget
    win_shell: choco install wget -y
    retries: 3
    delay: 5
  - name: Pull down hybrid directoy
    win_shell: git clone {{theRepo}}  c:\k\hybrid
    ignore_errors: yes
  - name: Pull openvswitch
    win_shell: wget.exe https://cloudbase.it/downloads/openvswitch-hyperv-2.7.0-certified.msi -O openvswitch.msi
  - name: Install open vswitch
    win_shell: msiexec /i openvswitch.msi ADDLOCAL="OpenvSwitchCLI,OpenvSwitchDriver,OVNHost" /qn
    ignore_errors: yes
  - name: Turn off Advfireall profiles
    win_shell: NetSh Advfirewall set allprofiles state off
  - name: Set up path for ovn
    win_shell: setx PATH "C:\Program Files\Cloudbase Solutions\Open vSwitch\bin;$env:path" -m
  - name: Start ovs service
    win_shell: Start-Service ovs-vswitchd
# Setup the network on windows machines
- hosts: windows
  gather_facts: no
  serial: 1
  tasks:
  - name: Expand System Disk
    win_shell: expanddisk.ps1
    args:
      chdir: c:\k\hybrid\3.9\bin
  - name: Prepare to create docker network
    win_scheduled_task:
      name: docker-create
      description: Create The Docker Network
      executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive c:\k\hybrid\3.9\bin\docker-create.ps1
      frequency: once
      enabled:   true
      time:      "14:00:00"
      user:      SYSTEM
  - name: Execute the creation of the docker network
    win_shell: Start-ScheduledTask -TaskName docker-create
  - name: Pause for Docker Setup
    pause:
       minutes: 1
  - name: Prepare to setup the windows sdn setup
    win_scheduled_task:
      name: setup-network
      description: Create The Docker Network
      executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive c:\k\hybrid\3.9\bin\setup-network.ps1
      frequency: once
      enabled:   true
      time:      "14:00:00"
      user:      SYSTEM
  - name: Pause for preparation of sdn setup
    pause:
       minutes: 1
  - name: Execute the setup of the windows sdn
    win_shell: Start-ScheduledTask -TaskName setup-network
  - name: Pause for sdn setup completion
    pause:
       minutes: 1
# Main Windows Setup
- hosts: masters
  gather_facts: no
  tasks:
  - name: Restart atomic-openshift-master-controllers.service
    shell: systemctl restart atomic-openshift-master-controllers.service
  - name: Restart atomic-openshift-master-api.service
    shell: systemctl restart atomic-openshift-master-api.service
  - name: Wait for clean restart
    pause:
       minutes: 2
- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  tasks:
  - name: set up environment
    shell: ln -f -s -n /etc/origin/ openshift.local.config
    args:
       chdir: /etc/origin
    delegate_to: "{{ groups.masters | first }}"
  - name: Create Config
    shell: oc adm create-node-config --hostnames={{inventory_hostname}} --node={{inventory_hostname}} --node-dir=/etc/origin/generated-configs/{{inventory_hostname}}
    args:
        chdir: /etc/origin/
    delegate_to: "{{ groups.masters | first }}"
  - name: Create archives per host
    archive:
       path: /etc/origin/generated-configs/{{inventory_hostname}}/*
       dest: /etc/origin/generated-configs/{{inventory_hostname}}.tgz
    delegate_to: "{{ groups.masters | first }}"
- hosts: masters[0]
  become: yes
  become_user: root
  tasks:
  - name: Create a archive of the node configs
    archive:
       path: /etc/origin/generated-configs/*
       dest:  /etc/origin/generated-configs.tgz
       mode:  666
  - name: Move the configs to bastion
    fetch:
       src:  /etc/origin/generated-configs.tgz
       dest:  /tmp/
       flat: yes
       become: yes
  - name: Create the ovn scc account
    shell: oc create serviceaccount ovn
    ignore_errors: yes
  - name: add scc privileged for ovn
    shell: oc adm policy add-scc-to-user privileged -z ovn
  - name: Add the cluster role
    shell: oc adm policy add-cluster-role-to-user cluster-admin -z ovn
  - name: Save the token for later usage
    shell: oc sa get-token ovn
    register: ovn_key
  - local_action: copy content={{ ovn_key.stdout }} dest=/root/ovn.token
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  vars_files:
   - /etc/ansible/parameters.vars
  tasks:
  - name: Setup local origin structure
    file:
          path: /etc/origin/generated-configs
          state: directory
  - name: Extract configs
    unarchive:
       src: /tmp/generated-configs.tgz
       dest: /etc/origin/generated-configs
  - name: Fix the access mode
    file:
      path: /etc/origin/generated-configs
      owner: "{{user}}"
      recurse: yes
    ignore_errors: yes
  - name: Create windows directory for node files
    file:
         path: "/etc/origin/generated-configs/node-{{ groups.masters | first }}/windows"
         state: directory
  - name: Fix system-node kubconfig
    copy:
       src: "/etc/origin/generated-configs/node-{{ groups.masters | first }}.{{InternalDomain}}/system:node:{{ groups.masters | first }}.{{InternalDomain}}.kubeconfig"
       dest: "/etc/origin/generated-configs/node-{{ groups.masters | first }}/windows/system-node-{{ groups.masters | first }}.{{InternalDomain}}.kubeconfig"
       force: yes
  - name: Fix system-node crt
    copy:
       src: "/etc/origin/generated-configs/node-{{ groups.masters | first }}.{{InternalDomain}}/system:node:{{ groups.masters | first }}.{{InternalDomain}}.crt"
       dest: "/etc/origin/generated-configs/node-{{ groups.masters | first }}/windows/system-node-{{ groups.masters | first }}.{{InternalDomain}}.crt"
       force: yes
  - name: Fix system-node key
    copy:
       src: "/etc/origin/generated-configs/node-{{ groups.masters | first }}.{{InternalDomain}}/system:node:{{ groups.masters | first }}.{{InternalDomain}}.key"
       dest: "/etc/origin/generated-configs/node-{{ groups.masters | first }}/windows/system-node-{{ groups.masters | first }}.{InternalDomain}}.key"
       force: yes
  - name: Flush arp cache
    shell: ip -s -s neigh flush all
- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  tasks:
  - name: Pull the kubernetes client
    win_shell: wget.exe --no-check-certificate https://dl.k8s.io/v1.9.9/kubernetes-node-windows-amd64.tar.gz -O C:\Windows\Temp\kubernetes.tar.gz
    async: 3600
    poll: 5 
  - name: Unzip kubernetes
    win_shell: 7z x -aoa C:\Windows\Temp\kubernetes.tar.gz -o\Windows\Temp
  - name: Untar kubernetes
    win_shell: 7z x -aoa c:\Windows\Temp\kubernetes.tar -o\Windows\Temp
  - name: Move the kube to bin
    win_shell: copy "C:\Windows\Temp\kubernetes\node\bin\*" C:\bin
  - name: Mkdir \k
    win_file:
       path: C:\k
       state: directory
       ignore_errors: yes
  - name: move the node files
    win_copy:
      src: /etc/origin/generated-configs/{{inventory_hostname}}.tgz
      dest: c:\k\{{inventory_hostname}}.tgz
      force: yes
  - name: Unzip the config files
    win_shell: 7z x -aoa /k/{{inventory_hostname}}.tgz  -o\k\
  - name: Unarchvie the config files
    win_shell: 7z x -aoa /k/etc/origin/generated-configs/{{inventory_hostname}}.tgz -o/k
  - name: Add the master cluster config file
    win_copy:
       src: "/etc/origin/generated-configs/node-{{ groups.masters | first }}/windows/"
       dest: /k/
       force: yes
  - name: Cleanup archive path
    win_file:
       path: c:\k\etc
       state: absent
  - name: Setup client config
    win_copy:
       src: "/root/.kube/config"
       dest: /k/config
       force: yes
  - name: Set kubeconfig
    win_shell: "[System.Environment]::SetEnvironmentVariable('KUBECONFIG', 'c:/k/config;c:/k/system-node-1.masters | first }}.kubeconfig', [System.EnvironmentVariableTarget]::Machine)"
  - name: Set kubeconfig
    win_shell: "[System.Environment]::SetEnvironmentVariable('KUBECONFIG', 'c:/k/config;c:/k/system-node-{{ groups.masters | first }}.kubeconfig')"
  - name: Pull down windowsservercore 1709
    win_shell: docker pull microsoft/windowsservercore:1709
    async: 3600
    poll: 5
  - name: Tag The image
    win_shell: docker tag microsoft/windowsservercore:1709 microsoft/windowsservercore:latest
  - name: Build the pause windows container
    win_shell: docker build . -t kubeletwin/pause
    args:
      chdir: c:\k\hybrid\3.9
# Part 2
- hosts: masters[0]
  become: yes
  become_user: root
  tasks:
  - name: Get the ovn_k8s.conf
    fetch:
          src: /etc/openvswitch/ovn_k8s.conf
          dest: "{{playbook_dir}}/"
          flat: yes
- hosts: windows
  tasks:
  - name: Create the master directory
    file: path="{{playbook_dir}}/{{ ansible_hostname }}" state=directory
    delegate_to: localhost
  - name: Create ovn_k8s.conf
    blockinfile:
      dest: "{{playbook_dir}}/{{ ansible_hostname }}/ovn_k8s.conf"
      create: yes
      block: |
         [default]
         encap-ip="{{lookup('dig',"{{ ansible_hostname }}")}}"

         [kubernetes]
         apiserver="{{lookup('file', '{{playbook_dir}}/api_host.txt')}}"  # kubernetes api server, or the load balanced address for the multiple api server case
         token="{{lookup('file', '{{playbook_dir}}/ovn.token')}}"
         cacert=/k/ca.crt

         [ovnnorth]
         address="tcp://{{lookup('dig',groups.masters | first )}}:6641" # this master machine's IP address

         [ovnsouth]
         address="tcp://{{lookup('dig',groups.masters | first )}}:6642"

    delegate_to: localhost
- hosts: windows
  gather_facts: no
  tasks:
  - name: Mkdir \cni
    win_file:
       path: C:\cni
       state: directory
       ignore_errors: yes
  - name: Create 10-ovn-kubernetes.conf
    win_copy:
       dest: c:\cni\10-ovn-kubernetes.conf
       force: yes
       content: |
        {"cniVersion":"0.3.1","name":"ovn-kubernetes","type":"ovn-k8s-cni-overlay","ipam":{},"dns":{}}

  - name: Copy ovn_k8s.conf to cni directory
    win_copy:
       src: "{{playbook_dir}}/{{ansible_hostname}}/ovn_k8s.conf"
       dest: C:\cni\ovn_k8s.conf
       force: yes
  - name: Copy ovn_k8s.conf to windows nodes
    win_copy:
       src: "{{playbook_dir}}/{{ansible_hostname}}/ovn_k8s.conf"
       dest: C:\Program Files\Cloudbase Solutions\Open vSwitch\conf\ovn_k8s.conf
       force: yes
  - name: copy ovn-k8s-cni-overlay.exe
    win_copy:
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
       dest: /bin/ovn-k8s-cni-overlay.exe
       force: yes
  - name: copy ovn ovnkube.exe
    win_copy:
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovnkube.exe
       dest: /bin/ovnkube.exe
       force: yes
- hosts: windows
  gather_facts: no
  tasks:
  - name: Add port 10250 to windows firewall rules
    win_shell: New-NetFirewallRule -Name kubelet -DisplayName 'Kubernetes Node' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 10250
    ignore_errors: yes
  - name: Add port 6081 to windows firewall rules
    win_shell: New-NetFirewallRule -Name ovn.6081 -DisplayName 'ovn.6081' -Enabled True -Direction Inbound -Protocol UDP -Action Allow -LocalPort 6081
    ignore_errors: yes
  - name: Install NSSM
    win_shell: choco install nssm -y
    ignore_errors: yes
# Part 2
- hosts: windows
  gather_facts: no
  tasks:
  - name: Set up the GUID for openvswitch
    win_shell: "$GUID = (New-Guid).Guid; Write-Output $GUID"
    register: guid
  - debug: msg="GUID is {{ guid.stdout }}"
  - name: create a schedule task
    win_scheduled_task:
      name: ovnsetguid
      description: Set OVN System Guid
      executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive ovs-vsctl set Open_vSwitch . external_ids:system-id="{{ guid.stdout | trim  }}"
      frequency: once
      enabled:   true
      user:      SYSTEM
      time:      "14:00:00"
  - name: Run the schedule task
    win_shell: Start-ScheduledTask -TaskName ovnsetguid -AsJob
  - name: Setup Kubeovn Service
    win_shell: setup_kubeovn_service.ps1
    args:
      chdir: \k\hybrid\3.9\bin
  - name: Setup Kubelet Service
    win_shell: setup_kubelet_service.ps1
    args:
      chdir: \k\hybrid\3.9\bin
  - name: Enable kubeovn
    win_shell: Set-Service kubeovn -StartupType Automatic
  - name: Start kubeovn
    win_shell: Start-Service kubeovn
  - name: Enable kubelet
    win_shell: Set-Service kubelet -StartupType Automatic
  - name: Start kubelet
    win_shell: Start-Service kubelet
#Part 3
- hosts: windows
  gather_facts: no
  tasks:
  - name: Setup Kubeovn Service
    win_shell: setup_kubeovn_service.ps1
    args:
      chdir: \k\hybrid\3.9\bin
  - name: Setup Kubelet Service
    win_shell: setup_kubelet_service.ps1
    args:
      chdir: \k\hybrid\3.9\bin
  - name: Enable kubeovn
    win_shell: Set-Service kubeovn -StartupType Automatic
  - name: Start kubeovn
    win_shell: Start-Service kubeovn
  - name: Enable kubelet
    win_shell: Set-Service kubelet -StartupType Automatic
  - name: Start kubelet
    win_shell: Start-Service kubelet
