apiVersion: v1
kind: Pod
metadata:
  labels:
    name: winpacman
  name: winpacman
spec:
  containers:
  - image: glennswest/winpacman
    imagePullPolicy: Always
    name: winpacman
    ports:
    - containerPort: 80
      protocol: TCP
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  nodeSelector:
    beta.kubernetes.io/os: windows
  restartPolicy: Always
  securityContext:
    privileged: true

