- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Create destination directory
    file: path=/opt/cni/bin state=directory
  - name: Create directory for cni plugins
    file: path=/tmp/cniplugin state=directory
  - name: Get cni plugins
    shell: wget -q https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz; tar xvzf cni-plugins-amd64-v0.7.1.tgz -C /tmp/cniplugin
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: Create /opt/cni/bin
    file: path=/opt/cni/bin state=directory
  - name: Push the cni loopback plugin to all nodes
    copy:
      src: /tmp/cniplugin/loopback
      dest: /opt/cni/bin/loopback
      mode: u+rwx
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
  - name: open firewall 6641
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6641 -j ACCEPT
  - name: open firewall 6642
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6642 -j ACCEPT
  - name: open firewall 6081
    shell: iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 6081 -j ACCEPT
  - name: Save iptables rules
    shell: service iptables save
- hosts: masters
  become: yes
  become_user: root
  tasks:
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}

- hosts: masters
  become: yes
  become_user: root
  tasks:
  - name: Remove OVS DB Content
    shell: rm -rf /var/lib/openvswitch/ovn*.db
  - name: Remove any old ovn-kubernets
    shell: rm -r -f ~/ovn-kubernetes
  - name: Clone ovn-kubernetes
    shell: git clone https://github.com/openvswitch/ovn-kubernetes ~/ovn-kubernetes
  - name: Provision the OVN Namespace
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovn-namespace.yaml
    ignore_errors: yes
  - name: Provision the OVN Policy
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovn-policy.yaml
    ignore_errors: yes
  - name: Provision the OVN Project
    shell: oc project ovn-kubernetes
    ignore_errors: yes
  - name: Add adm policy auyuid
    shell: oc adm policy add-scc-to-user anyuid -z ovn
    ignore_errors: yes
  - name: Run the ovn-setup
    shell: ./ovn-kubernetes/dist/ansible/scripts/ovn-setup.sh
    ignore_errors: yes
  - name: Start the ovn-ovs daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/sdn-ovs.yaml
    ignore_errors: yes
  - name: Start the master ovn daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovnkube-master.yaml
    ignore_errors: yes
  - name: Start the node ovn daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovnkube.yaml
    ignore_errors: yes
