- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: open firewall 6641
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6641 -j ACCEPT
  - name: open firewall 6642
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6642 -j ACCEPT
  - name: open firewall 6081
    shell: iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 6081 -j ACCEPT
  - name: Save iptables rules
    shell: service iptables save
  - name: Remove OVS DB Content
    shell: rm -rf /var/lib/openvswitch/ovn*.db
  - name: Remove any old ovn-kubernets
    shell: rm -r -f ~/ovn-kubernetes
  - name: Clone ovn-kubernetes
    shell: git clone https://github.com/openvswitch/ovn-kubernetes ~/ovn-kubernetes
  - name: Revert back a PR (442)
    shell: ~/ovn-kubernetes; git pull origin pull/442/head
  - name: Provision the OVN Namespace
    shell: oc create -f /root/openshift-windows/3.11/kubeovn/ovn-namespace.yaml
    ignore_errors: yes
  - name: Provision the OVN Policy
    shell: oc create -f /root/openshift-windows/3.11/kubeovn/ovn-policy.yaml
    ignore_errors: yes
  - name: Provision the OVN Project
    shell: oc project ovn-kubernetes
    ignore_errors: yes
  - name: Add adm policy auyuid
    shell: oc adm policy add-scc-to-user anyuid -z ovn
    ignore_errors: yes
  - name: Run the ovn-setup
    shell: cd ~/ovn-kubernetes/dist/ansible/scripts; ./ovn-setup.sh
    ignore_errors: yes
  - name: Start the ovn-ovs daemonset
    shell: oc create -f /root/openshift-windows/3.11/kubeovn/sdn-ovs.yaml
    ignore_errors: yes
  - name: Start the master ovn daemonset
    shell: oc create -f /root/openshift-windows/3.11/kubeovn/ovnkube-master.yaml
    ignore_errors: yes
